
# travis config

sudo: required

language: r
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release

before_install:
  - R -e "install.packages(c('pkgload','roxygen2','tinytest'))"
  - ./document.sh
  - cd ./pkg

r_packages:
  - covr
  - rmarkdown


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


